# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Make it Move
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

url: "https://sparkglug.co.uk"
repository: "Patrick-Thomas/Patrick-Thomas.github.io" 

staticman_url: https://sparkglug.herokuapp.com/v3/entry/github/Patrick-Thomas/Patrick-Thomas.github.io/master/comments

reCaptcha:
    siteKey: 6LfHTtMZAAAAAGH6Q2_lHYGojMTBG01HolkvAPaK
    secret: G8bIN9ic8IRwA3f80t2Eqe7IDUoUna8PI5tpor47eNhO6KY9dctwS0aiHWei0uVYoQbqM5uzFHSUuddTfcySbJS4Ky7ywgwPEIsBBrzx2lR4mYwc0/9R5oXyLi5jAakep9QYcq4RU0iTIxec1Eu4JIiccRA6FAmnkiEFIcMhKun6wDELfVtPthxZ3q1M1fnCRaP7ILtbaRAkBWhSbhABun1x/x11I7J7FOslDJ7xU2lSg6Tg70VELFdc0nNUlpPUkR6A75Tgx0/TVc0Xgi+OkIo/YuzAhgSga80e1mg/DCO0qDKveYXkwm2FtgpOe7gPAU4Ecb7UOlpF027izwdM+jTlg5BpY2UptBguKnmy8GxH0+PE9iC6ktpGxHOEOhsZRNA3KxZ/4MAdtp2YSqf21D1y5LFlJ7JAI/aLSHFVTnN4mevScSsqXW6WvWNwsvSxy8ctsizNb+55HKlGQkPMc04o+3h102hQ7CkRG4DNdbo57hJou2JqDLN1JKJbm2YrSzb3X7rgbNJ8XBmlLDBBYzdswLc1EnlHcTTH2IxGt7sBAcYMtwmxykKT8n9FwQy1YjegzyyKgbyX8vqTK/6tKOWloo7UYvq/HuHHfIgwsfuhCyNIFZMj9VBj7cWzGfTv8EJ2cG5yhxmBS/Hqv1kXICa4l+U3tWi9PSYN8Ey6mmk=

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Patrick Thomas"
  avatar : "/assets/images/paddy-photo.jpg"
  bio    : "I'm an engineer who never quite found what I enjoy doing the most, so I ended up doing a bit of everything. Here are some interesting things I've learned along the way"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Patrick-Thomas"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/patrick-thomas-43947562/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/lifeglug"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Patrick-Thomas"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/patrick-thomas-43947562/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/lifeglug"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
